/*
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthPostRequestBody;
import io.swagger.client.model.Error;
import io.swagger.client.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * Issues a JWT
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authTest() throws ApiException {
        AuthPostRequestBody authPostRequestBody = null;
        InlineResponse200 response = api.auth(authPostRequestBody);

        // TODO: test validations
    }
    
}
