/*
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentationApi
 */
@Ignore
public class DocumentationApiTest {

    private final DocumentationApi api = new DocumentationApi();

    
    /**
     * Returns an OpenAPI 3.0 spec.
     *
     * Returns an OpenAPI 3.0 spec describing HTTP methods, endpoints, parameters, etc.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDocsTest() throws ApiException {
        Object response = api.getDocs();

        // TODO: test validations
    }
    
}
