/*
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GoogleApi
 */
@Ignore
public class GoogleApiTest {

    private final GoogleApi api = new GoogleApi();

    
    /**
     * Get Google OAuth tokens
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGoogleAuthTokensTest() throws ApiException {
        String code = null;
        InlineResponse2003 response = api.getGoogleAuthTokens(code);

        // TODO: test validations
    }
    
    /**
     * Get Google OAuth URL
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGoogleAuthUrlTest() throws ApiException {
        InlineResponse2002 response = api.getGoogleAuthUrl();

        // TODO: test validations
    }
    
}
