/*
 * Docket API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.ForgotPasswordPostRequestBody;
import io.swagger.client.model.ResetPasswordPostRequestBody;
import io.swagger.client.model.User;
import io.swagger.client.model.UsersPostRequestBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * Confirms user&#39;s registration
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void confirmUserTest() throws ApiException {
        String code = null;
        api.confirmUser(code);

        // TODO: test validations
    }
    
    /**
     * Create a user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UsersPostRequestBody usersPostRequestBody = null;
        User response = api.createUser(usersPostRequestBody);

        // TODO: test validations
    }
    
    /**
     * Forgot password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forgotPasswordTest() throws ApiException {
        ForgotPasswordPostRequestBody forgotPasswordPostRequestBody = null;
        api.forgotPassword(forgotPasswordPostRequestBody);

        // TODO: test validations
    }
    
    /**
     * Reset password
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resetPasswordTest() throws ApiException {
        ResetPasswordPostRequestBody resetPasswordPostRequestBody = null;
        api.resetPassword(resetPasswordPostRequestBody);

        // TODO: test validations
    }
    
}
